### ISSUE TITLE
Doesn't work on mars.

### ISSUE THREAD

**Issue by PietPtr** [Tijndagamer/RaspberryPiGPIO#1]
I have found a critical bug in RaspberryPiGPIO/Accelerometer/ADXL345.py

As a martian, I have tested this since I need a good open source driver for my accelerometers. However, it doesn't seem to output the correct values, so my ship crashed into a mountain!

Please fix this quickly, for the Mars's sake...

**Comment by m-rtijn** [comment]
Sure, what's the gravity on mars in m/s^2?

**Comment by PietPtr** [comment]
http://bit.ly/1Jq9gmR

**Comment by m-rtijn** [comment]
This issue has been fixed in update 1.1.1.
